# This is the Build docker-compose.yml file. You can build and Run ChurchCRM
# from this file by first filling in your password and db info in the .env
# file and then running "docker-compose build", "docker-compose up" in terminal.

version: '3'

services:

  database: #Name of DB Host
    container_name: database
    image: nimmis/docker-alpine-mariadb
    environment:
      - MYSQL_DB_HOST=database
      - MYSQL_ROOT_PASSWORD=changeme
      - MYSQL_DATABASE=churchcrm
      - MYSQL_USER=churchcrm
      - MYSQL_PASSWORD=changeme
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == worker]

  churchcrm:
    container_name: churchcrm
    image: mydarkfire/churchcrm
    ports:
      - "8084:80"
    environment:
      - MYSQL_DB_HOST=database
      - MYSQL_ROOT_PASSWORD=changeme
      - MYSQL_DATABASE=churchcrm
      - MYSQL_USER=churchcrm
      - MYSQL_PASSWORD=changeme
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]